<?php
$this->options['selections'] = array (
	'button_size' => array (
		'code' => array (
			'LG',
			'SM',
		),
		'text' => array (
			'Normal',
			'Small',
		),
	),

	'charset' => array (
		'code' => array (
			'Big5',
			'EUC-JP',
			'EUC-KR',
			'EUC-TW',
			'gb2312',
			'gbk',
			'HZ-GB-2312',
			'ibm-862',
			'ISO-2022-CN',
			'ISO-2022-JP',
			'ISO-2022-KR',
			'ISO-8859-1',
			'ISO-8859-2',
			'ISO-8859-3',
			'ISO-8859-4',
			'ISO-8859-5',
			'ISO-8859-6',
			'ISO-8859-7',
			'ISO-8859-8',
			'ISO-8859-9',
			'ISO-8859-13',
			'ISO-8859-15',
			'KOI8-R',
			'Shift_JIS',
			'UTF-7',
			'UTF-8',
			'UTF-16',
			'UTF-32',
			'US-ASCII',
			'windows-1250',
			'windows-1251',
			'windows-1252',
			'windows-1253',
			'windows-1254',
			'windows-1255',
			'windows-1256',
			'windows-1257',
			'windows-1258',
			'windows-874',
			'windows-949',
			'x-mac-greek',
			'x-mac-turkish',
			'x-mac-centraleurroman',
			'x-mac-cyrillic',
			'ebcdic-cp-us',
			'ibm-1047',
		),
		'text' => array (
			'Big5 (Traditional Chinese in Taiwan)',
			'EUC-JP',
			'EUC-KR',
			'EUC-TW',
			'gb2312 (Simplified Chinese)',
			'gbk',
			'HZ-GB-2312 (Traditional Chinese in Hong Kong)',
			'ibm-862 (Hebrew with European characters)',
			'ISO-2022-CN',
			'ISO-2022-JP',
			'ISO-2022-KR',
			'ISO-8859-1 (Western European Languages)',
			'ISO-8859-2',
			'ISO-8859-3',
			'ISO-8859-4',
			'ISO-8859-5',
			'ISO-8859-6',
			'ISO-8859-7',
			'ISO-8859-8',
			'ISO-8859-9',
			'ISO-8859-13',
			'ISO-8859-15',
			'KOI8-R (Cyrillic)',
			'Shift_JIS',
			'UTF-7',
			'UTF-8',
			'UTF-16',
			'UTF-32',
			'US-ASCII',
			'windows-1250',
			'windows-1251',
			'windows-1252',
			'windows-1253',
			'windows-1254',
			'windows-1255',
			'windows-1256',
			'windows-1257',
			'windows-1258',
			'windows-874 (Thai)',
			'windows-949 (Korean)',
			'x-mac-greek',
			'x-mac-turkish',
			'x-mac-centraleurroman',
			'x-mac-cyrillic',
			'xebcdic-cp-us',
			'ibm-1047',
		),
	),
	'cmd' => array (
		'code' => array (
			'_cart',
			'_xclick',
		),
		'text' => array (
			'Cart',
			'BuyNow',
		),
	),
	'cs' => array (
		'code' => array (
			0,
			1,
		),
		'text' => array (
			'White',
			'Black',
		),
	),
	'currency_code' => array (
		'code' => array (
			'AUD',
			'BRL',
			'CAD',
			'CHF',
			'CZK',
			'DKK',
			'EUR',
			'GBP',
			'HKD',
			'HUF',
			'ILS',
			'JPY',
			'MYR',
			'MXN',
			'NOK',
			'NZD',
			'PHP',
			'PLN',
			'SGD',
			'SEK',
			'THB',
			'TWD',
			'USD',
		),
		'text' => array (
			'Australian Dollar',
			'Brazilian Real',
			'Canadian Dollar',
			'Swiss Franc',
			'Czech Koruna',
			'Danish Krone',
			'Euro',
			'Pound Sterling ',
			'Hong Kong Dollar',
			'Hungarian Forint',
			'Israeli New Sheqel',
			'Japanese Yen ',
			'Malaysian Ringgit',
			'Mexican Peso',
			'Norwegian Krone',
			'New Zealand Dollar',
			'Philippine Peso',
			'Polish Zloty',
			'Singapore Dollar',
			'Swedish Krona',
			'Thai Baht',
			'Taiwan New Dollar',
			'U.S. Dollar',
		),
	),

	'item_desc' => array (
		'code' => array (
			'Album_Photo',
			'Album_Photo_Filename',
			'Album_Photo_Media',
			'Album_Photo_Media_Size',
			'Album_Photo_Size',
			'Album_Photo_Size_Media',
		),
		'text' => array (
			'Album; Photo;',
			'Album; Photo; Filename;',
			'Album; Photo; Media;',
			'Album; Photo; Media; Size;',
			'Album; Photo; Size;',
			'Album; Photo; Size; Media;',
		),
	),

	'no_note' => array (
		'code' => array (
			0,
			1,
		),
		'text' => array (
			"The buyer can't add a comment",
			'The buyer can add a comment',
		),
	),
	'no_shipping' => array (
		'code' => array (
			0,
			1,
			2,
		),
		'text' => array (
			'To invite the buyer to type a shipping address',
			"The buyer can't adding a shipping address",
			'The buyer must be adding a shipping address',
		),
	),

	'page_style' => array (
		'code' => array (
			'paypal',
			'primary',
			'custom',
		),
		'text' => array (
			'use the PayPal page style',
			'use the page style marked as primary',
			'use the custom payment page style.',
		),
	),

	'rm' => array (
		'code' => array (
			0,
			1,
			2,
		),
		'text' => array (
			'Full GET method',
			'Browser by GET, but not transactions variables',
			'Full POST method',
		),
	),

	'use_button_encrypted' => array (
		'code' => array (
			0,
			1,
		),
		'text' => array (
			'No',
			'Yes',
		),
	),
	'use_tax_rate' => array (
		'code' => array (
			0,
			1,
		),
		'text' => array (
			'No',
			'Yes',
		),
	),

	'viewing_pricelist' => array (
		'code' => array (
			0,
			1,
		),
		'text' => array (
			'No',
			'Yes',
		),
	),
);

?>
